# This is a basic workflow to help you get started with Actions

name: Libva CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: environment variables
      run: printenv
    # Runs a single command using the runners shell
    - name: prepare workspace 
      run: |
        sudo apt-get install -y build-essential autoconf automake libtool m4 lcov \
          perl pkg-config libdrm-dev autoconf libegl1-mesa-dev libgl1-mesa-dev \
          libwayland-dev libx11-dev libxext-dev libxfixes-dev

    # Runs a set of commands using the runners shell
    - name: build libva
      run: |
        ./autogen.sh
        ./configure --prefix=/usr
        make -j4
        sudo make install
        make check 
